// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG2mp-TcoiZIQJs8vKQBqsLhKpAbutceg',
    appId: '1:279948758907:web:11836e2c5c66a6f59737de',
    messagingSenderId: '279948758907',
    projectId: 'spree-bpgc',
    authDomain: 'spree-bpgc.firebaseapp.com',
    databaseURL: 'https://spree-bpgc-default-rtdb.firebaseio.com',
    storageBucket: 'spree-bpgc.appspot.com',
    measurementId: 'G-VTCLR7XYNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTeka2GmkP4WI7_e_7HMF3OyUpw63Uo9Q',
    appId: '1:279948758907:android:43044ddf903e1a2b9737de',
    messagingSenderId: '279948758907',
    projectId: 'spree-bpgc',
    databaseURL: 'https://spree-bpgc-default-rtdb.firebaseio.com',
    storageBucket: 'spree-bpgc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsr9PGH_LAieDLMLSWZu6iAvnypv4cbPA',
    appId: '1:279948758907:ios:f7f27474d35295d69737de',
    messagingSenderId: '279948758907',
    projectId: 'spree-bpgc',
    databaseURL: 'https://spree-bpgc-default-rtdb.firebaseio.com',
    storageBucket: 'spree-bpgc.appspot.com',
    iosBundleId: 'com.example.spreePortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsr9PGH_LAieDLMLSWZu6iAvnypv4cbPA',
    appId: '1:279948758907:ios:69cb5031396e1a019737de',
    messagingSenderId: '279948758907',
    projectId: 'spree-bpgc',
    databaseURL: 'https://spree-bpgc-default-rtdb.firebaseio.com',
    storageBucket: 'spree-bpgc.appspot.com',
    iosBundleId: 'com.example.spreePortal.RunnerTests',
  );
}
